### ISSUE TITLE
Crash on setting a condition

### ISSUE THREAD

**Issue by DcNdrew** [XFactHD/RecipeBuilder#3]
I tried to make a shapeless recipe for testing. A Farmer's Delight dough and a lime dye to make a bread.
I clicked on Set condition, and crash:
https://pastebin.com/CRn0P4zm

**Comment by XFactHD** [comment]
The current version of RecipeBuilder is not compatible with 1.18.2 due to the heavy internal changes done by Mojang in this update.
Unfortunately I won't be able to release a fix for this just yet because I am in the middle of heavily reworking a few things.
For now your best option is to use RecipeBuilder in a separate instance with 1.18.1. As long as the internal names of items or tags weren't changed by mod authors between the 1.18.1 and 1.18.2 versions, the generated data will work just fine.

I'll keep this issue open until a new version for 1.18.2 is out.

**Comment by XFactHD** [comment]
Please excuse the extreme delay. I have finally found the time to properly update RecipeBuilder to 1.18.2. I decided to not release the planned reworks for the time being and will most likely ship them with the next update, which hopefully won't take as long as this one.
