### ISSUE TITLE
Recipes Wont Load in

### ISSUE THREAD

**Issue by DGiraffe-Gaming** [XFactHD/RecipeBuilder#8]
every once in a while all my recipes stop working.... and even tho they still exist in the datapack they dont load into the game.... not sure why

**Comment by XFactHD** [comment]
This mod only generates the recipes once and doesn't touch them anymore after that, so any issues you may be encountering are outside of anything that could be caused by this mod.
The only assumption I can make is that you are entering a different world and since the datapack is only present in the world you generated the recipes in, the recipes won't be available in any other world. If you want to use the recipes in another world, you have to copy the generated datapack from the `recipebuilder` folder to the datapacks folder in the new world.

Since you haven't provided any additional information, this is all I can tell you. For any further assistance, I would need to know the Minecraft version, Forge version, RecipeBuilder version and the debug log from when this happened on https://gist.github.com (if you are using CurseForge, you'll have to enable the debug log in the CurseForge app first).

**Comment by XFactHD** [comment]
Closing due to lack of feedback. If the advise I gave above didn't fix it or you are otherwise still having issues with this, please provide the requested information and I will reopen this issue if necessary.
